### ISSUE TITLE
enable use of esys

### ISSUE THREAD

**Issue by flihp** [flihp/tpm2-tcti-sgx#18]
will require getting tpm2-tss / libtss2-esys building with https://github.com/intel/intel-sgx-ssl

**Comment by junyuanw** [comment]
Hi, flihp
Do you schedule about this plan? we want to run tpm2-tss in enclave, thanks!

**Comment by flihp** [comment]
Hi junyuanw. I do not currently have plans to continue working on this unfortunately. It was a fun idea but my recent work has taken me in a different direction. I should probably close this issue and archive the repo but feel free to fork it and make it useful for whatever your purposes are.
